apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      labels:
        app: api-produto    
    spec:
      containers:
      - name: api-produto
        image: vonsoski/luqman-abdi:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: NodePort
  selector:
    app: api-produto
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008